### ISSUE TITLE
koolproxy运行提示init https engine failed

### ISSUE THREAD

**Issue by Black-Steel** [ilxp/koolproxy#9]
我用immortalwrt源码(内核6.1)编译luci-app-ikoolproxy,成功编译并能运行，但是无法过滤https视频，终端命令运行koolproxy，提示init https engine faild.所需要的依赖也都安装了，这个是什么原因呢？如何解决？

**Comment by jkle112** [comment]
降低內核到5.4。
測試21版（內核5.4），22版，雖然都是openssl1.1.1，但是22版（內核5.10）會無限重啓。
